### ISSUE TITLE
note: find new solution for quotation marks

### ISSUE THREAD

**Issue by vera-charvat** [lu-pl/cortab#4]
https://github.com/lu-pl/cortab/blob/fb2cd338e68cd6e8f364edddd1205652f1aa61e0/cortab/example_output/corpustable.ttl#L6753

Maybe we can eliminate some of the quotations marks in the corpusTable comments, so the comments look cleaner.. ?

**Comment by lu-pl** [comment]
The values are taken from the corpusTable as they are and triple quotes are valid Turtle (see [quoted literals](https://www.w3.org/TR/turtle/#turtle-literals)). I think we could stick with that, but I don't mind changing it either.

**Comment by vera-charvat** [comment]
Ok, I'll close this for now.
